### ISSUE TITLE
Rome - block import errors

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#199]
Symptoms: High CPU usage, and lagging in blocks relative to the network.
This is a known bug, that will be fixed upstream.
Solution: Only option now is to restart the joystream-node.

We are seeing an error on some but not all nodes, that is pointing to failed assertion in the executive:

https://github.com/paritytech/substrate/blob/c37bb08535c49a12320af7facfd555ce05cce2e8/srml/executive/src/lib.rs#L277

It is not happening consistently at same time, and its not clear yet if its happening when attempting to import a specific block.

```
Mar 22 07:34:17 localhost joystream-node[1977]: ====================
Mar 22 07:34:17 localhost joystream-node[1977]: Version: 2.1.2-441c04b-x86_64-linux-gnu
Mar 22 07:34:17 localhost joystream-node[1977]:    0: substrate_panic_handler::set::{{closure}}
Mar 22 07:34:17 localhost joystream-node[1977]:    1: std::panicking::rust_panic_with_hook
Mar 22 07:34:17 localhost joystream-node[1977]:              at src/libstd/panicking.rs:475
Mar 22 07:34:17 localhost joystream-node[1977]:    2: std::panicking::begin_panic
Mar 22 07:34:17 localhost joystream-node[1977]:    3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Mar 22 07:34:17 localhost joystream-node[1977]:    4: joystream_node_runtime::api::dispatch
Mar 22 07:34:17 localhost joystream-node[1977]:    5: std::panicking::try::do_call
Mar 22 07:34:17 localhost joystream-node[1977]:    6: __rust_maybe_catch_panic
Mar 22 07:34:17 localhost joystream-node[1977]:              at src/libpanic_unwind/lib.rs:78
Mar 22 07:34:17 localhost joystream-node[1977]:    7: substrate_executor::native_executor::safe_call
Mar 22 07:34:17 localhost joystream-node[1977]:    8: std::thread::local::LocalKey<T>::with
Mar 22 07:34:17 localhost joystream-node[1977]:    9: <joystream_node::service::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
Mar 22 07:34:17 localhost joystream-node[1977]:   10: std::thread::local::LocalKey<T>::with
Mar 22 07:34:17 localhost joystream-node[1977]:   11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Mar 22 07:34:17 localhost joystream-node[1977]:   12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
Mar 22 07:34:17 localhost joystream-node[1977]:   13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Mar 22 07:34:17 localhost joystream-node[1977]:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
Mar 22 07:34:17 localhost joystream-node[1977]:   15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Mar 22 07:34:17 localhost joystream-node[1977]:   16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Mar 22 07:34:17 localhost joystream-node[1977]:   17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Mar 22 07:34:17 localhost joystream-node[1977]:   18: substrate_consensus_common::import_queue::import_single_block
Mar 22 07:34:17 localhost joystream-node[1977]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Mar 22 07:34:17 localhost joystream-node[1977]:   20: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll
Mar 22 07:34:17 localhost joystream-node[1977]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Mar 22 07:34:17 localhost joystream-node[1977]:   22: futures_executor::thread_pool::PoolState::work
Mar 22 07:34:17 localhost joystream-node[1977]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 22 07:34:17 localhost joystream-node[1977]:   24: std::panicking::try::do_call
Mar 22 07:34:17 localhost joystream-node[1977]:   25: __rust_maybe_catch_panic
Mar 22 07:34:17 localhost joystream-node[1977]:              at src/libpanic_unwind/lib.rs:78
Mar 22 07:34:17 localhost joystream-node[1977]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 22 07:34:17 localhost joystream-node[1977]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Mar 22 07:34:17 localhost joystream-node[1977]:              at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022

Mar 22 07:34:17 localhost joystream-node[1977]:   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Mar 22 07:34:17 localhost joystream-node[1977]:              at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022
Mar 22 07:34:17 localhost joystream-node[1977]:       std::sys_common::thread::start_thread
Mar 22 07:34:17 localhost joystream-node[1977]:              at src/libstd/sys_common/thread.rs:13
Mar 22 07:34:17 localhost joystream-node[1977]:       std::sys::unix::thread::Thread::new::thread_start
Mar 22 07:34:17 localhost joystream-node[1977]:              at src/libstd/sys/unix/thread.rs:80
Mar 22 07:34:17 localhost joystream-node[1977]:   29: start_thread
Mar 22 07:34:17 localhost joystream-node[1977]:   30: __clone
Mar 22 07:34:17 localhost joystream-node[1977]: Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /home/travis/.cargo/git/checkouts/substrate-7e08433d4c370a21/c37bb08/srml/executive/src/lib.rs:277
Mar 22 07:34:17 localhost joystream-node[1977]: This is a bug. Please report it at:
Mar 22 07:34:17 localhost joystream-node[1977]:         https://www.joystream.org/
Mar 22 07:34:17 localhost joystream-node[1977]: 2020-03-22 07:34:17 Block import error:
Mar 22 07:34:17 localhost joystream-node[1977]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
Mar 22 07:34:17 localhost joystream-node[1977]: Hash: given=37e53f18a5c2bdb9fa308008985cfaf5c56bc5d60c34c8fbf8d9a8432b4afb18, expected=a76c8388406dbc0dcf0c716eef277152b16aaac8547bcd63871a4606db5e60d4
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201703380142370/1201703470532354) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
```rust
// check storage root.
let storage_root = new_header.state_root();
header.state_root().check_equal(&storage_root);

// This assertion is failing
assert!(header.state_root() == storage_root, "Storage root must match that calculated.");
```

**Comment by mnaamani** [comment]
During the period when these errors were being logged the CPU consistently at very high inbound traffic. Perhaps the high inbound traffic was an attack?

The node appears to have continued to import blocks despite these logs.

<img width="913" alt="Screen Shot 2020-03-22 at 2 32 49 PM" src="https://user-images.githubusercontent.com/1621012/77247395-40dfa600-6c4a-11ea-8e99-6f2fa6b413e1.png">

**Comment by mnaamani** [comment]
Seems it is related to this issue: https://github.com/paritytech/substrate/issues/5112
