### ISSUE TITLE
Cli Error trying to setUri

### ISSUE THREAD

**Issue by Sulejman** [Joystream/joystream#2128]
Hello, I'm getting lots of type error trying to set connection URL:

```
joystream-cli api:setUri
Unable to resolve type ChannelId, it will fail on construction
Unable to resolve type LeadId, it will fail on construction
Unable to resolve type CuratorOpeningId, it will fail on construction
Unable to resolve type CuratorApplicationIdToCuratorIdMap, it will fail on construction
Unable to resolve type CuratorApplicationId, it will fail on construction
Unable to resolve type MintId, it will fail on construction
Unable to resolve type MintBalanceOf, it will fail on construction
Unable to resolve type RationaleText, it will fail on construction
Unknown types found, no types for ActivateOpeningAt, ApplicationOf, BalanceOfMint, Channel, ChannelContentType, ChannelCurationStatus, ChannelId, ChannelPublicationStatus, ClassPermissionsType, ClassPropertyValue, Credential, CredentialSet, CurationActor, Curator, CuratorApplication, CuratorApplicationId, CuratorApplicationIdSet, CuratorApplicationIdToCuratorIdMap, CuratorOpening, CuratorOpeningId, ElectionParameters, ElectionStage, ElectionStake, HiringApplicationId, Lead, LeadId, Mint, MintBalanceOf, MintId, OpeningOf, OpeningPolicyCommitment, Operation, OptionalText, PaidMembershipTerms, PaidTermId, Principal, PrincipalId, RationaleText, Recipient, RecipientId, ReferenceConstraint, RewardPolicy, RewardRelationship, RewardRelationshipId, SealedVote, Seats, Stake, StakeId, ThreadCounter, TransferableStake, WorkerOf, WorkingGroupUnstaker
Unable to resolve type PaidTermId, it will fail on construction
2021-02-02 12:06:03        API/INIT: Error: FATAL: Unable to initialize the API: createType(PaidTermId):: Cannot construct unknown type PaidTermId
    at EventEmitter.value (/Users/sule/Documents/GitHub/joystream/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95676) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(PaidTermId):: Cannot construct unknown type PaidTermId
    at EventEmitter.value (/Users/sule/Documents/GitHub/joystream/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:95676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Sulejman** [comment]
Resolved by flushing old state.json file from the app data directory.
