### ISSUE TITLE
Thread 'tokio-runtime-worker' panicked at 'not implemented'

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#2337]
Anyone seen this? `/root/.cargo/git` does not exist.

```
Apr 08 12:03:04.609  INFO 💤 Idle (73 peers), best: #13153 (0x1380…69e6), finalized #13151 (0x5e01…8517), ⬇ 353.0kiB/s ⬆ 361.1kiB/s
Apr 08 12:03:06.275  INFO ✨ Imported #13154 (0x5494…557e)
Apr 08 12:03:06.623  INFO ♻️  Reorg on #13154,0x5494…557e to #13154,0x1603…2018, common ancestor #13153,0x1380…69e6
Apr 08 12:03:06.623  INFO ✨ Imported #13154 (0x1603…2018)
Apr 08 12:03:06.626  WARN Error sending a subscription update: ConnectionClosed

====================

Version: 5.1.0-9d9e77751-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/panicking.rs:50:5
   7: <futures::sink::send_all::SendAll<T,U> as futures::future::Future>::poll
   8: <futures::future::select::Select<A,B> as futures::future::Future>::poll
   9: futures::future::chain::Chain<A,B,C>::poll
  10: futures::task_impl::std::set
  11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  12: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  13: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  24: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  25: tokio::runtime::task::raw::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: tokio::runtime::context::enter
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys/unix/thread.rs:71:17
  31: start_thread
  32: clone


Thread 'tokio-runtime-worker' panicked at 'not implemented', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/2cd2096/client/rpc/src/author/mod.rs:218

This is a bug. Please report it at:

        https://www.joystream.org/
```

**Comment by mnaamani** [comment]
Thanks for reporting. Will investigate

**Comment by shamil-gadelshin** [comment]
Do you mind sharing the full starting command line? @traumschule

**Comment by mnaamani** [comment]
And perhaps what transaction you maybe have submitted to the node at the time this occurred, what client you were using and what version of polkadot-js api if applicable?

**Comment by traumschule** [comment]
`./joystream-node --chain joy-testnet-5.json --pruning archive --validator --rpc-cors all` ([linux binary](https://github.com/Joystream/helpdesk/tree/master/roles/validators#setup-node-1))

BTW a user reported an error in `#bug-reports` that could be related, didn`t submit any transactions myself.

**Comment by mnaamani** [comment]
It is not clear what happened exactly and without being able to reproduce the condition its difficult to find a solution. If it happens again we can investigate further.
