### ISSUE TITLE
helios type errors

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#2583]
current master (ed82a115e468d96c27ae6ed4e85da348c345e499) fails:
```
$ /home/joystream/joystream/node_modules/.bin/helios
node:internal/modules/cjs/loader:352
      throw err;
      ^

Error: Cannot find module '/home/joystream/joystream/node_modules/@joystream/types/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:344:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:557:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/joystream/joystream/storage-node/packages/runtime-api/index.js:24:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/joystream/joystream/node_modules/@joystream/types/package.json',
  requestPath: '@joystream/types'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

After `yarn add @joystream/types`:
```
$ yarn helios
yarn run v1.22.10
$ /home/joystream/joystream/node_modules/.bin/helios
Found 3 staked providers

Resolving live provider API Endpoints...
resolve failed for id 3 this.base.api.query.storageWorkingGroup.workerStorage is not a function
resolve failed for id 4 this.base.api.query.storageWorkingGroup.workerStorage is not a function
resolve failed for id 2 this.base.api.query.storageWorkingGroup.workerStorage is not a function

Checking API Endpoints are online
3 No url set, skipping
4 No url set, skipping
2 No url set, skipping
/home/joystream/joystream/storage-node/packages/runtime-api/assets.js:195
    this._cachedEntries = await this.base.api.query.dataDirectory.dataByContentId.entries()
                                                                                  ^

TypeError: Cannot read property 'entries' of undefined
    at AssetsApi.fetchDataObjects (/home/joystream/joystream/storage-node/packages/runtime-api/assets.js:195:83)
    at main (/home/joystream/joystream/storage-node/packages/helios/bin/cli.js:101:24)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by traumschule** [comment]
Keep running into it.

**Comment by mnaamani** [comment]
I'm not sure why you are running `yarn add @joystream/types`

try this:

```
yarn
yarn workspace @joystream/types build
yarn helios
```

**Comment by traumschule** [comment]
Thanks!

> I'm not sure why you are running `yarn add @joystream/types`

Just a guess because it was not documented: #2779
