### ISSUE TITLE
Olympia query node - null prevention error

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2609]
It seems are Olympia tests are falling on `null` prevention feature (which seems to be working fine in Sumer environment).

```
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'forum_thread_id' of undefined, stack: TypeError: Cannot read property 'forum_thread_id' of undefined
    at sanitizeNullCharacter (/joystream/node_modules/@joystream/hydra-processor/lib/db/subscribers.js:37:16)
    at sanitizeEntity (/joystream/node_modules/@joystream/hydra-processor/lib/db/subscribers.js:30:9)
    at SanitizationSubscriber.beforeInsert (/joystream/node_modules/@joystream/hydra-processor/lib/db/subscribers.js:11:9)
```

Explore the cause of the problem and fix it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201711088269929) by [Unito](https://www.unito.io)

**Comment by ondratra** [comment]
The issue has already been solved by PRs https://github.com/Joystream/hydra/pull/453, https://github.com/Joystream/hydra/pull/469, and #2986.
