### ISSUE TITLE
Query node - silent desync

### ISSUE THREAD

**Issue by ondratra** [Joystream/joystream#2620]
On 7 September, a team member noticed that the query node is returning different results for the same query when repeated multiple times. Initial suspicion that one of two Hydra servers that are behind a balancer is out of sync was confirmed. Namely `hydra1` server. Two days of events were not reflected. Restarting `joystream-node` and `indexer` resolved the issue and made the server catch up. It is possible that `joystream-node` got somehow disconnected from the rest of the network and needed to be restarted to reconnect - this is my unsubstantiated explanation.

After looking into the indexer log on the problematic server, it was apparent that the indexer was not receiving new blocks from the node without any apparent reason. Logs were not containing any useful explanation for that, but I will attach the logs from the relevant days to this ticket in case it's useful in the future. The problem seems to start on 5. September and restart of service happened around 7/8 September midnight.

Even if we don't find out the reason behind it, we could maybe set up some monitoring for the servers, so we are alerted as soon as possible when the next incident happens. We could periodically send a query to the query node and ask for the processed block height.

**Comment by ondratra** [comment]
Relevant parts of logs:
[indexer.log](https://github.com/Joystream/joystream/files/7131269/indexer.log)
[joystream-node.log](https://github.com/Joystream/joystream/files/7131314/joystream-node.log)

It seems that issue occured around the time of block `2159098`.

Relevant parts in indexer log:
1) Indexer crashed:
```
{"log":"2021-09-05T04:50:50.182Z index-builder:redis-relayer Relaying to redis: hydra:indexer:complete:block {\"height\":2159098,\"events\":[{\"name\":\"system.ExtrinsicSuccess\",\"id\":\"0000000002159098-000000\"},{\"name\":\"system.ExtrinsicSuccess\",\"id\":\"0000000002159098-000001\"}],\"ts\":1630817450182}\n","stream":"stderr","time":"2021-09-05T04:50:50.182799096Z"}
{"log":"2021-09-05T04:50:50.184Z index-builder:status-server Updating the indexer head from 2159097 to 2159098\n","stream":"stderr","time":"2021-09-05T04:50:50.184495883Z"}
{"log":"2021-09-05T04:50:50.184Z index-builder:status-server Updated the indexer head to 2159098\n","stream":"stderr","time":"2021-09-05T04:50:50.184969612Z"}
{"log":"2021-09-05T05:00:50.152Z index-builder:pooled-executor Error getting next generator value\n","stream":"stderr","time":"2021-09-05T05:00:50.15295935Z"}
{"log":"2021-09-05T05:00:50.157Z index-builder:pooled-executor Generator is done, exiting\n","stream":"stderr","time":"2021-09-05T05:00:50.158028458Z"}
{"log":"2021-09-05T05:00:50.157Z index-builder:pooled-executor Generator is done, exiting\n","stream":"stderr","time":"2021-09-05T05:00:50.158064518Z"}
{"log":"2021-09-05T05:00:50.157Z index-builder:pooled-executor Generator is done, exiting\n","stream":"stderr","time":"2021-09-05T05:00:50.158070408Z"}
{"log":"2021-09-05T05:00:50.157Z index-builder:pooled-executor Generator is done, exiting\n","stream":"stderr","time":"2021-09-05T05:00:50.158075267Z"}
{"log":"2021-09-05T05:00:50.158Z index-builder:indexer Index builder has been stopped\n","stream":"stderr","time":"2021-09-05T05:00:50.158696266Z"}
{"log":"2021-09-05T05:00:50.159Z index-builder:producer Block producer has been stopped\n","stream":"stderr","time":"2021-09-05T05:00:50.159372874Z"}
{"log":"2021-09-05T05:00:50.159Z index-builder:query-node Stopping the query node\n","stream":"stderr","time":"2021-09-05T05:00:50.159398125Z"}
{"log":"2021-09-05T05:00:50.159Z index-builder:manager Trying to stop the query node\n","stream":"stderr","time":"2021-09-05T05:00:50.159422185Z"}
{"log":"2021-09-05T05:00:50.160Z index-builder:query-node Query node state: 5\n","stream":"stderr","time":"2021-09-05T05:00:50.160273853Z"}
{"log":"2021-09-05T05:00:50.160Z index-builder:query-node Query node is not running\n","stream":"stderr","time":"2021-09-05T05:00:50.160288272Z"}
{"log":"2021-09-05T05:00:50.162Z index-builder:manager Closing the database connection\n","stream":"stderr","time":"2021-09-05T05:00:50.162374788Z"}
{"log":"Error: Error getting next generator value, {} name: Error, message: Timed out: no block has been produced within last 600000 seconds, stack: Error: Timed out: no block has been produced within last 600000 seconds\n","stream":"stdout","time":"2021-09-05T05:00:50.169401042Z"}
{"log":"    at Timeout.\u003canonymous\u003e (/home/hydra/packages/hydra-common/lib/utils/wait-for.js:80:20)\n","stream":"stdout","time":"2021-09-05T05:00:50.169430811Z"}
{"log":"    at listOnTimeout (internal/timers.js:554:17)\n","stream":"stdout","time":"2021-09-05T05:00:50.169435741Z"}
{"log":"    at processTimers (internal/timers.js:497:7)\n","stream":"stdout","time":"2021-09-05T05:00:50.169439571Z"}
{"log":"    at poller (/home/hydra/packages/hydra-indexer/lib/indexer/PooledExecutor.js:67:27)\n","stream":"stdout","time":"2021-09-05T05:00:50.169443981Z"}
{"log":"2021-09-05T05:00:50.169Z index-builder:query-node Query node state: 5\n","stream":"stderr","time":"2021-09-05T05:00:50.169878871Z"}
{"log":"2021-09-05T05:00:50.171Z index-builder:query-node Query node is not running\n","stream":"stderr","time":"2021-09-05T05:00:50.171754557Z"}
{"log":"error Command failed with exit code 1.\n","stream":"stderr","time":"2021-09-05T05:00:50.324580425Z"}
```
2) After all services were restarted (everything have been working since then):
```
{"log":"2021-09-07T23:12:48.935Z index-builder:query-node Api is ready\n","stream":"stderr","time":"2021-09-07T23:12:48.935615504Z"}
{"log":"2021-09-07T23:12:48.935Z index-builder:redis-factory Using redis://redis:6379/0 for Redis clients\n","stream":"stderr","time":"2021-09-07T23:12:48.936116693Z"}
{"log":"2021-09-07T23:12:48.942Z index-builder:indexer Spawned worker.\n","stream":"stderr","time":"2021-09-07T23:12:48.942823379Z"}
{"log":"2021-09-07T23:12:48.952Z index-builder:status-server Subscribed to the indexer channels\n","stream":"stderr","time":"2021-09-07T23:12:48.952667557Z"}
{"log":"2021-09-07T23:12:48.953Z index-builder:indexer Last indexed block in the database: 2159098\n","stream":"stderr","time":"2021-09-07T23:12:48.953372425Z"}
{"log":"2021-09-07T23:12:48.953Z index-builder:indexer Got block height hint: 717988\n","stream":"stderr","time":"2021-09-07T23:12:48.953423845Z"}
{"log":"2021-09-07T23:12:48.953Z index-builder:indexer WARNING! The database contains indexed blocks.\n","stream":"stderr","time":"2021-09-07T23:12:48.953440395Z"}
{"log":"          The last indexed block height is 2159098. The indexer \n","stream":"stderr","time":"2021-09-07T23:12:48.953445515Z"}
{"log":"          will continue from block 2159098 ignoring the start \n","stream":"stderr","time":"2021-09-07T23:12:48.953449535Z"}
{"log":"          block height hint. Set the environment variable FORCE_BLOCK_HEIGHT to true \n","stream":"stderr","time":"2021-09-07T23:12:48.953453245Z"}
{"log":"          if you want to start from 717988 anyway.\n","stream":"stderr","time":"2021-09-07T23:12:48.953459225Z"}
{"log":"2021-09-07T23:12:48.953Z index-builder:indexer Starting the block indexer at block 2159099\n","stream":"stderr","time":"2021-09-07T23:12:48.953496035Z"}
```

3) In node logs, I can see one interesting thing around the time indexer crashed - reorg happened:
```
{"log":"Sep 05 04:50:12.650  INFO ✨ Imported #\u001b[1;37m2159095\u001b[0m (0xd0a0…71aa)    \n","stream":"stderr","time":"2021-09-05T04:50:12.65118366Z"}
{"log":"Sep 05 04:50:12.895 TRACE execute_block: Batch-verification: 0 pending tasks, 0 sr25519 signatures    {block}\n","stream":"stderr","time":"2021-09-05T04:50:12.895551304Z"}
{"log":"Sep 05 04:50:12.895 TRACE execute_block: Finalization of batch verification took 0 ms    {block}\n","stream":"stderr","time":"2021-09-05T04:50:12.895705134Z"}
{"log":"Sep 05 04:50:12.898  INFO ♻️  Reorg on #\u001b[1;31m2159095\u001b[0m,0xd0a0…71aa to #\u001b[1;32m2159095\u001b[0m,0x4d23…1f73, common ancestor #\u001b[1;37m2159094\u001b[0m,0xed95…d3ba    \n","stream":"stderr","time":"2021-09-05T04:50:12.900070074Z"}
{"log":"Sep 05 04:50:12.900  INFO ✨ Imported #\u001b[1;37m2159095\u001b[0m (0x4d23…1f73)    \n","stream":"stderr","time":"2021-09-05T04:50:12.900228473Z"}
{"log":"Sep 05 04:50:13.480  INFO 💤 \u001b[1;37mIdle\u001b[0m (\u001b[1;37m50\u001b[0m peers), best: #\u001b[1;37m2159095\u001b[0m (0x4d23…1f73), finalized #\u001b[1;37m2159092\u001b[0m (0x4438…0cdd), \u001b[32m⬇ 53.3kiB/s\u001b[0m \u001b[31m⬆ 60.5kiB/s\u001b[0m    \n","stream":"stderr","time":"2021-09-05T04:50:13.480823469Z"}
{"log":"Sep 05 04:50:18.481  INFO 💤 \u001b[1;37mIdle\u001b[0m (\u001b[1;37m50\u001b[0m peers), best: #\u001b[1;37m2159095\u001b[0m (0x4d23…1f73), finalized #\u001b[1;37m2159093\u001b[0m (0x327f…5820), \u001b[32m⬇ 56.0kiB/s\u001b[0m \u001b[31m⬆ 57.8kiB/s\u001b[0m    \n","stream":"stderr","time":"2021-09-05T04:50:18.481292248Z"}
```

**Comment by ondratra** [comment]
As pointed out by @shamil-gadelshin, reorgs are quite common and shouldn't be a problem. There is a more important log message `Error importing block` in node's logs:
```
{"log":"Sep 05 04:50:43.120 TRACE execute_block: Finalization of batch verification took 0 ms    {block}\n","stream":"stderr","time":"2021-09-05T04:50:43.120985468Z"}
{"log":"Sep 05 04:50:43.132  INFO ✨ Imported #\u001b[1;37m2159099\u001b[0m (0x1c5f…6034)    \n","stream":"stderr","time":"2021-09-05T04:50:43.132490441Z"}
{"log":"Sep 05 04:50:43.482  INFO 💤 \u001b[1;37mIdle\u001b[0m (\u001b[1;37m50\u001b[0m peers), best: #\u001b[1;37m2159099\u001b[0m (0x1c5f…6034), finalized #\u001b[1;37m2159096\u001b[0m (0xf781…542c), \u001b[32m⬇ 53.9kiB/s\u001b[0m \u001b[31m⬆ 71.9kiB/s\u001b[0m    \n","stream":"stderr","time":"2021-09-05T04:50:43.482533402Z"}
{"log":"Sep 05 04:50:45.750  WARN 💔 Error importing block 0x86ec28f81bd1b032942b193795173f227c432e01953a6b32597ba980d0e227d2: Err(Other(ClientImport(\"Invalid operation in the pending changes tree: Tried to import or finalize node that is an ancestor of a previously finalized node\")))    \n","stream":"stderr","time":"2021-09-05T04:50:45.750967825Z"}
{"log":"Sep 05 04:50:48.482  INFO 💤 \u001b[1;37mIdle\u001b[0m (\u001b[1;37m50\u001b[0m peers), best: #\u001b[1;37m2159099\u001b[0m (0x1c5f…6034), finalized #\u001b[1;37m2159097\u001b[0m (0x4148…1a15), \u001b[32m⬇ 67.8kiB/s\u001b[0m \u001b[31m⬆ 59.7kiB/s\u001b[0m    \n","stream":"stderr","time":"2021-09-05T04:50:48.482675399Z"}
```

The cause is not yet known.

**Comment by ondratra** [comment]
Closing this one down since we haven't experienced the problem for more than a year now.
