### ISSUE TITLE
Query node failure processing members.MemberVerificationStatusUpdated event

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#3323]
Looks like a bad type definition in our types library?

```
INFO: Processing block: 0000005861-6d561, events count: 1 
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'params' of undefined, stack: TypeError: Cannot read property 'params' of undefined
    at MemberVerificationStatusUpdatedEvent.get params [as params] (/joystream/query-node/mappings/lib/generated/types/members.js:113:87)
    at members_MemberVerificationStatusUpdated (/joystream/query-node/mappings/lib/src/membership.js:170:108)
    at MappingsLookupService.call (/joystream/node_modules/@joystream/hydra-processor/lib/executor/MappingsLookupService.js:80:15)
    at /joystream/node_modules/@joystream/hydra-processor/lib/executor/TransactionalExecutor.js:40:43
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: {} name: Error, message: TypeError: Cannot read property 'params' of undefined, stack: Error: TypeError: Cannot read property 'params' of undefined
    at MappingsProcessor.processingLo
```

![](https://user-images.githubusercontent.com/1621012/155952257-65e0d4a0-5553-43c9-8588-3c0fca435692.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201709380879215/1201892187238802) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Fixed in https://github.com/Joystream/joystream/pull/3324
