### ISSUE TITLE
Olympia validator won't start: The Trust Settings Record was corrupted

### ISSUE THREAD

**Issue by singulart** [Joystream/joystream#3480]
MacOS Big Sur 

```
➜  joystream git:(master) ./target/release/joystream-node --name isonar --pruning archive --validator --chain testnets/joy-testnet-6.json
Mar 23 22:44:49.701  INFO Joystream Node
Mar 23 22:44:49.701  INFO ✌️  version 6.5.0-c57054eebe-x86_64-macos
Mar 23 22:44:49.701  INFO ❤️  by Joystream contributors, 2019-2022
Mar 23 22:44:49.701  INFO 📋 Chain specification: Joystream
Mar 23 22:44:49.701  INFO 🏷  Node name: isonar
Mar 23 22:44:49.701  INFO 👤 Role: AUTHORITY
Mar 23 22:44:49.701  INFO 💾 Database: RocksDb at /Users/sonar/Library/Application Support/joystream-node/chains/joy_testnet_6/db
Mar 23 22:44:49.701  INFO ⛓  Native runtime: joystream-node-5 (joystream-node-0.tx1.au10)
Mar 23 22:44:55.353  INFO 🔨 Initializing Genesis block/state (state: 0x2425…81a1, header-hash: 0x00ad…71a4)
Mar 23 22:44:55.382  INFO 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
Mar 23 22:44:55.617  INFO ⏱  Loaded block-time = 6000 milliseconds from genesis on first-launch
Mar 23 22:44:55.617  INFO 👶 Creating empty BABE epoch changes on what appears to be first startup.
Mar 23 22:44:55.618  INFO 🏷  Local node identity is: 12D3KooWSY9wqboxncTp6BvUQPsYbf6Eba1ahqXeqBBQS7vVwr8L (legacy representation: 12D3KooWSY9wqboxncTp6BvUQPsYbf6Eba1ahqXeqBBQS7vVwr8L)

====================

Version: 6.5.0-c57054eebe-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:595:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:497:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:493:5
   7: core::panicking::panic_fmt
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/panicking.rs:92:14
   8: core::option::expect_none_failed
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/option.rs:1300:5
   9: hyper_rustls::connector::HttpsConnector<hyper::client::connect::http::HttpConnector>::new
  10: sc_offchain::api::http::SharedClient::new
  11: sc_offchain::OffchainWorkers<Client,Storage,Block>::new
  12: sc_service::builder::build_offchain_workers
  13: joystream_node::service::new_full
  14: sc_cli::runner::Runner<C>::run_node_until_exit
  15: joystream_node::command::run
  16: joystream_node::main
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: std::rt::lang_start::{{closure}}
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/rt.rs:51:25
  20: _main


Thread 'main' panicked at 'cannot access native cert store: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } }', /Users/sonar/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.21.0/src/connector.rs:46

This is a bug. Please report it at:

	https://www.joystream.org/

➜  joystream git:(master)
```

**Comment by traumschule** [comment]
Similar but not exact upstream also mac related https://github.com/paritytech/substrate/issues/5442

**Comment by singulart** [comment]
Fixed this specific error by detecting and removing the corrupted certificate: 

`/usr/bin/security delete-certificate -c "common name of the corrupt certificate" -t`

The error about corrupted trust settings went away, now I experience the error that is reported separately: https://github.com/Joystream/joystream/issues/3481
