### ISSUE TITLE
Olympia full node won't start: ResponseTooLong

### ISSUE THREAD

**Issue by singulart** [Joystream/joystream#3481]
MacOS Big Sur

```
➜  joystream git:(master) ✗ ./target/release/joystream-node --chain testnets/joy-testnet-6.json
Mar 23 23:47:10.520  INFO Joystream Node
Mar 23 23:47:10.520  INFO ✌️  version 6.5.0-c57054eebe-x86_64-macos
Mar 23 23:47:10.520  INFO ❤️  by Joystream contributors, 2019-2022
Mar 23 23:47:10.520  INFO 📋 Chain specification: Joystream
Mar 23 23:47:10.520  INFO 🏷  Node name: burly-brick-5672
Mar 23 23:47:10.520  INFO 👤 Role: FULL
Mar 23 23:47:10.520  INFO 💾 Database: RocksDb at /Users/sonar/Library/Application Support/joystream-node/chains/joy_testnet_6/db
Mar 23 23:47:10.520  INFO ⛓  Native runtime: joystream-node-5 (joystream-node-0.tx1.au10)
Mar 23 23:47:16.162  INFO 🔨 Initializing Genesis block/state (state: 0x2425…81a1, header-hash: 0x00ad…71a4)
Mar 23 23:47:16.243  INFO 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
Mar 23 23:47:16.514  INFO ⏱  Loaded block-time = 6000 milliseconds from genesis on first-launch
Mar 23 23:47:16.515  INFO 👶 Creating empty BABE epoch changes on what appears to be first startup.
Mar 23 23:47:16.526  INFO 🏷  Local node identity is: 12D3KooWBArHoWap7jFddssG6aahq9fMQuqRCVZtRA8qmEkv6yXx (legacy representation: 12D3KooWBArHoWap7jFddssG6aahq9fMQuqRCVZtRA8qmEkv6yXx)
Mar 23 23:47:16.543  INFO 📦 Highest known block at #0
Mar 23 23:47:16.544  INFO 〽️ Prometheus server started at 127.0.0.1:9615
Mar 23 23:47:16.554  INFO Listening for new connections on 127.0.0.1:9944.

====================

Version: 6.5.0-c57054eebe-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/std/src/panicking.rs:702:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/std/src/panicking.rs:588:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/std/src/sys_common/backtrace.rs:138:18
   6: rust_begin_unwind
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/std/src/panicking.rs:584:5
   7: core::panicking::panic_fmt
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/core/src/panicking.rs:143:14
   8: core::result::unwrap_failed
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/core/src/result.rs:1784:5
   9: <libp2p_mdns::behaviour::Mdns as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  10: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  11: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  12: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler,TConnInfo>::poll_next_event
  13: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  14: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  15: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  18: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: std::thread::local::LocalKey<T>::with
  21: futures_executor::local_pool::block_on
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: std::panicking::try
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: tokio::runtime::context::enter
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/alloc/src/boxed.rs:1853:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/alloc/src/boxed.rs:1853:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e95b10ba4ac4564ed25f7eef143e3182c33b3902/library/std/src/sys/unix/thread.rs:108:17
  31: __pthread_start


Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ResponseTooLong', /Users/sonar/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-mdns-0.22.0/src/behaviour.rs:296

This is a bug. Please report it at:

	https://www.joystream.org/

➜  joystream git:(master) ✗
```

**Comment by mnaamani** [comment]
Unfortunately I don't have access to a `MacOS Big Sur` and it seems to be something networking OS specific. If someone else can try to reproduce and debug perhaps we might get some more insight.
