### ISSUE TITLE
tokio-runtime-worker: `watch_extrinsic` `subscriptions.add` not implemented

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#3499]
just experienced  'tokio-runtime-worker' panicked at 'not implemented', should be fixed on [master](https://github.com/paritytech/substrate/blob/master/client/rpc/src/author/mod.rs#L221)

```
Mar 27 16:37:36.286  INFO ✨ Imported #57324 (0xe6dc…a645)    
Mar 27 16:37:36.351  WARN Error sending a subscription update: ConnectionClosed    
Mar 27 16:37:36.351  INFO ♻️  Reorg on #57324,0xe6dc…a645 to #57324,0xdd31…893d, common ancestor #57323,0x7b93…a7b1    
Mar 27 16:37:36.352  INFO ✨ Imported #57324 (0xdd31…893d)    

====================

Version: 6.5.0-c57054eebe-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:495:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/core/src/panicking.rs:50:5
   7: futures::sink::send_all::SendAll<T,U>::try_start_send
   8: <futures::sink::send_all::SendAll<T,U> as futures::future::Future>::poll
   9: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  10: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  11: futures::future::chain::Chain<A,B,C>::poll
  12: futures::task_impl::std::set
  13: futures::task_impl::Spawn<T>::poll_fn_notify
  14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  19: tokio::runtime::task::raw::poll
  20: std::thread::local::LocalKey<T>::with
  21: tokio::runtime::thread_pool::worker::Context::run_task
  22: tokio::runtime::thread_pool::worker::Context::run
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
  24: tokio::runtime::thread_pool::worker::run
  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  26: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  27: tokio::runtime::task::raw::poll
  28: tokio::runtime::blocking::pool::Inner::run
  29: tokio::runtime::context::enter
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/alloc/src/boxed.rs:1546:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9b471a3f5fe57e5c6e08acf665f2094422415a3d/library/std/src/sys/unix/thread.rs:71:17
  33: start_thread
  34: clone


Thread 'tokio-runtime-worker' panicked at 'not implemented', /home/joystream/.cargo/git/checkouts/substrate-7e08433d4c370a21/2cd2096/client/rpc/src/author/mod.rs:218
```

## Code
`.cargo/git/checkouts/substrate-7e08433d4c370a21/2cd2096/client/rpc/src/author/mod.rs`
```
     fn watch_extrinsic(&self,
                _metadata: Self::Metadata,
                subscriber: Subscriber<TransactionStatus<TxHash<P>, BlockHash<P>>>,
                xt: Bytes,
        ) {
                let submit = || -> Result<_> {
                        let best_block_hash = self.client.info().best_hash;
                        let dxt = TransactionFor::<P>::decode(&mut &xt[..])
                                .map_err(error::Error::from)?;
                        Ok(
                                self.pool
                                        .submit_and_watch(&generic::BlockId::hash(best_block_hash), TX_SOURCE, dxt)
                                        .map_err(|e| e.into_pool_error()
                                                .map(error::Error::from)
                                                .unwrap_or_else(|e| error::Error::Verification(Box::new(e)).into())
                                        )
                        )
                };

                let subscriptions = self.subscriptions.clone();
                let future = ready(submit())
                        .and_then(|res| res)
                        // convert the watcher into a `Stream`
                        .map(|res| res.map(|stream| stream.map(|v| Ok::<_, ()>(Ok(v)))))
                        // now handle the import result,
                        // start a new subscrition
                        .map(move |result| match result {
                                Ok(watcher) => {
                                        subscriptions.add(subscriber, move |sink| {
                                                sink
218:                                                        .sink_map_err(|_| unimplemented!())
                                                        .send_all(Compat::new(watcher))
                                                        .map(|_| ())
                                        });
                                },
                                Err(err) => {
                                        warn!("Failed to submit extrinsic: {}", err);
                                        // reject the subscriber (ignore errors - we don't care if subscriber is no longer there).
                                        let _ = subscriber.reject(err.into());
                                },
                        });
```

# Slashes

`staking.validatorSlashInEra` lists 13 slashes of 7% for era 94 (just before Sun Mar 27 12 UTC 2022, #55900), the strongest with **260.2950 kJOY** for orang3club (`5EHfoRcN9tVa3PJ2XVhsFecxtCVyu7dz1pQ7YmheerPR3tBm`). See [Chain State](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Folympia.joystreamstats.live%2Frpc#/chainstate) `staking.validatorSlashInEra`:
```
...
[
    [
      94
      5HMs7aB7N9yzk5c7UhLtAhnfnj6KbZXGVpXL3JvVzBA2FQ4U
    ]
    [
      7.00%
      5.4900 kJOY
    ]
  ]
  [
    [
      94
      5EHfoRcN9tVa3PJ2XVhsFecxtCVyu7dz1pQ7YmheerPR3tBm
    ]
    [
      7.00%
      260.2950 kJOY
    ]
  ]
  [
    [
      94
      5FxPr4Rzp1eqUkiaicZ4yvzdU5pNvccbrQKw9xhzuw7hgNdx
    ]
    [
      3.74%
      16.1140 kJOY
    ]
  ]
...
```

https://wiki.polkadot.network/docs/learn-staking#slashing
> The maximum slashing that can occur due to unresponsiveness is 7%. After around 45% of the validators go offline, the expression 3 (x - (n / 10 + 1))) / n will go beyond 1. Hence, min((3 (x - (n / 10 + 1))) / n, 1) * 0.07 will be ceiled to 7%.

With currently 23 validators 13 nodes would indeed amount for 56%. It should be checked if above report is related to an attack and if the current network is vulnerable.

Another prior slash happened in era 23 (`staking.earliestUnappliedSlash`).

**Comment by mnaamani** [comment]
cc: @shamil-gadelshin

**Comment by mnaamani** [comment]
Could you share how you produced this error on your node.

**Comment by traumschule** [comment]
runs with `./target/release/joystream-node --name joystreamstats --chain joy-testnet-6.json --pruning archive --validator -d ~/ --rpc-cors all` and endpoint is advertised [here](https://discord.com/channels/811216481340751934/812344657794301972/956268834149527552) so anyone could try (malicious) extrinsics.

**Comment by mnaamani** [comment]
Yes what I really meant was what was the extrinsic that caused this issue, and how did you send it into the node, via a custom script, the joystream-cli, or polkadot-js apps .. ?

**Comment by mnaamani** [comment]
Also just as a general best practice, I would avoid making any validator expose rpc externally.

**Comment by traumschule** [comment]
This was apparently a "mass slash" because a lot of validators stopped / forked and reorganizing took some time?

"recovered" this from our discord conversation => [more illustration](https://discord.com/channels/811216481340751934/812344657794301972/960217104559267860)
> my balance was slightly above 500k [before] and [now] stays at zero even after paying out rewards - is there some concept of staking/slashing debt? you can see my council stake unchanged  while the staking one was reduced by several M tJOY, because  penalties for each nomination

![](https://cdn.discordapp.com/attachments/812344657794301972/960217105326833764/profile.png)

same as Joystream/substrate-node-joystream/issues/63 and case mentioned in Joystream/pioneer/pull/3894
