### ISSUE TITLE
Carthage faucet fails with 500

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4040]
Some requests work, some fail. Not sure what the exact reproduction is. Faucet logs:

```
[2022-07-15 11:41:19]: Error: Number can only safely store up to 53 bits
    at assert (/faucet/node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js:6:21)
    at u128.toNumber (/faucet/node_modules/@polkadot/util/node_modules/bn.js/lib/bn.js:547:7)
    at JoyApi.invitingMemberHasTopUpBalance (/faucet/lib/joyApi.js:174:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async register (/faucet/lib/register.js:92:24)
    at async Mutex.<anonymous> (/faucet/lib/app.js:60:13)
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202613194582625) by [Unito](https://www.unito.io)

**Comment by mnaamani** [comment]
Thanks for catching, I was unsafely calling .toNumber() on a `u128` - Balance type which had over 1M JOY and caused an overflow.

**Comment by mnaamani** [comment]
Fixed in https://github.com/Joystream/membership-faucet/commit/c64f7e44166257d6035c4e82b398439c7ac791e6

**Comment by kdembler** [comment]
Closing then :)
