### ISSUE TITLE
QN: StorageSystemParameters.dataObjectStateBloatBondValue should be BigInt

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4108]
When updating the data object state bloat bond to a value greater than Int32 max:

```
processor                | ERROR: Stopping the proccessor due to errors: {
processor                |   "query": "UPDATE \"storage_system_parameters\" SET \"updated_at\" = $1, \"blacklist\" = $2, \"data_object_state_bloat_bond_value\" = $3, \"version\" = \"version\" + 1 WHERE \"id\" IN ($4) RETURNING \"version\"",
processor                |   "parameters": [
processor                |     "2022-08-01T17:14:51.000Z",
processor                |     [],
processor                |     10000000000,
processor                |     "1"
processor                |   ],
processor                |   "driverError": {
processor                |     "length": 112,
processor                |     "name": "error",
processor                |     "severity": "ERROR",
processor                |     "code": "22003",
processor                |     "file": "numutils.c",
processor                |     "line": "250",
processor                |     "routine": "pg_strtoint32"
processor                |   },
processor                |   "length": 112,
processor                |   "severity": "ERROR",
processor                |   "code": "22003",
processor                |   "file": "numutils.c",
processor                |   "line": "250",
processor                |   "routine": "pg_strtoint32"
processor                | } name: QueryFailedError, message: value "10000000000" is out of range for type integer, stack: QueryFailedError: value "10000000000" is out of range for type integer
processor                |     at QueryFailedError.TypeORMError [as constructor] (/joystream/node_modules/typeorm/error/TypeORMError.js:9:28)
processor                |     at new QueryFailedError (/joystream/node_modules/typeorm/error/QueryFailedError.js:13:28)
processor                |     at PostgresQueryRunner.<anonymous> (/joystream/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:294:31)
processor                |     at step (/joystream/node_modules/tslib/tslib.js:144:27)
processor                |     at Object.throw (/joystream/node_modules/tslib/tslib.js:125:57)
processor                |     at rejected (/joystream/node_modules/tslib/tslib.js:116:69)
processor                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
processor                | ERROR: {} name: Error, message: QueryFailedError: value "10000000000" is out of range for type integer, stack: Error: QueryFailedError: value "10000000000" is out of range for type integer
processor                |     at MappingsProcessor.processingLoop (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:75:23)
processor                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
processor                |     at async Promise.all (index 1)
processor                |     at async MappingsProcessor.start (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:25:9)
processor                |     at async ProcessorRunner.process (/joystream/node_modules/@joystream/hydra-processor/lib/start/ProcessorRunner.js:47:9)
processor                |     at async Run.run (/joystream/node_modules/@joystream/hydra-processor/lib/commands/run.js:27:13)
processor                |     at async Run._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
processor                |     at async Config.runCommand (/joystream/node_modules/@oclif/config/lib/config.js:173:24)
processor                |     at async Main.run (/joystream/node_modules/@oclif/command/lib/main.js:27:9)
processor                |     at async Main._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
processor                | INFO: Shutting down...
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202701317101391) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment]
Fixed in https://github.com/Joystream/joystream/pull/4110
