### ISSUE TITLE
Query node crashes when deleting channel assets as moderator

### ISSUE THREAD

**Issue by Lezek123** [Joystream/joystream#4109]
```
processor                | Content has been disconnected from Channel { channelId: '3', dataObjectId: '4' }
processor                | Content has been disconnected from Channel { channelId: '3', dataObjectId: '5' }
processor                | Channel assets have been removed { ids: [ <BN: 4>, <BN: 5> ] }
processor                | ERROR: Stopping the proccessor due to errors: {
processor                |   "query": "INSERT INTO \"channel_assets_deleted_by_moderator_event\"(\"id\", \"created_at\", \"created_by_id\", \"updated_at\", \"updated_by_id\", \"deleted_at\", \"deleted_by_id\", \"version\", \"in_extrinsic\", \"in_block\", \"network\", \"index_in_block\", \"actor\", \"channel_id\", \"asset_ids\", \"rationale\") VALUES ($1, $2, $3, $4, DEFAULT, DEFAULT, DEFAULT, $5, $6, $7, $8, $9, DEFAULT, $10, $11, $12) RETURNING \"version\"",
processor                |   "parameters": [
processor                |     "OLYMPIA-5255-6",
processor                |     "2022-08-01T18:01:22.001Z",
processor                |     "-",
processor                |     "2022-08-01T18:01:22.001Z",
processor                |     1,
processor                |     "0x07af6e63dc4b7176ddbfc9c70ed6ec51806cad59c646b884e0a0b097c4a2b718",
processor                |     5255,
processor                |     "OLYMPIA",
processor                |     6,
processor                |     3,
processor                |     [
processor                |       4,
processor                |       5
processor                |     ],
processor                |     "Just testing"
processor                |   ],
processor                |   "driverError": {
processor                |     "length": 409,
processor                |     "name": "error",
processor                |     "severity": "ERROR",
processor                |     "code": "23502",
processor                |     "detail": "Failing row contains (OLYMPIA-5255-6, 2022-08-01 18:01:22.001, -, 2022-08-01 18:01:22.001, null, null, null, 1, 0x07af6e63dc4b7176ddbfc9c70ed6ec51806cad59c646b884e0a0b097c4a2b7..., 5255, OLYMPIA, 6, null, 3, {4,5}, Just testing).",
processor                |     "schema": "public",
processor                |     "table": "channel_assets_deleted_by_moderator_event",
processor                |     "column": "actor",
processor                |     "file": "execMain.c",
processor                |     "line": "1948",
processor                |     "routine": "ExecConstraints"
processor                |   },
processor                |   "length": 409,
processor                |   "severity": "ERROR",
processor                |   "code": "23502",
processor                |   "detail": "Failing row contains (OLYMPIA-5255-6, 2022-08-01 18:01:22.001, -, 2022-08-01 18:01:22.001, null, null, null, 1, 0x07af6e63dc4b7176ddbfc9c70ed6ec51806cad59c646b884e0a0b097c4a2b7..., 5255, OLYMPIA, 6, null, 3, {4,5}, Just testing).",
processor                |   "schema": "public",
processor                |   "table": "channel_assets_deleted_by_moderator_event",
processor                |   "column": "actor",
processor                |   "file": "execMain.c",
processor                |   "line": "1948",
processor                |   "routine": "ExecConstraints"
processor                | } name: QueryFailedError, message: null value in column "actor" violates not-null constraint, stack: QueryFailedError: null value in column "actor" violates not-null constraint
processor                |     at QueryFailedError.TypeORMError [as constructor] (/joystream/node_modules/typeorm/error/TypeORMError.js:9:28)
processor                |     at new QueryFailedError (/joystream/node_modules/typeorm/error/QueryFailedError.js:13:28)
processor                |     at PostgresQueryRunner.<anonymous> (/joystream/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:294:31)
processor                |     at step (/joystream/node_modules/tslib/tslib.js:144:27)
processor                |     at Object.throw (/joystream/node_modules/tslib/tslib.js:125:57)
processor                |     at rejected (/joystream/node_modules/tslib/tslib.js:116:69)
processor                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
processor                | ERROR: {} name: Error, message: QueryFailedError: null value in column "actor" violates not-null constraint, stack: Error: QueryFailedError: null value in column "actor" violates not-null constraint
processor                |     at MappingsProcessor.processingLoop (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:75:23)
processor                |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
processor                |     at async Promise.all (index 1)
processor                |     at async MappingsProcessor.start (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:25:9)
processor                |     at async ProcessorRunner.process (/joystream/node_modules/@joystream/hydra-processor/lib/start/ProcessorRunner.js:47:9)
processor                |     at async Run.run (/joystream/node_modules/@joystream/hydra-processor/lib/commands/run.js:27:13)
processor                |     at async Run._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
processor                |     at async Config.runCommand (/joystream/node_modules/@oclif/config/lib/config.js:173:24)
processor                |     at async Main.run (/joystream/node_modules/@oclif/command/lib/main.js:27:9)
processor                |     at async Main._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
processor                | INFO: Shutting down...
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202701522987906) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
- Who reported this?
- From what commit/branch?
- Why did integration tests not catch?

**Comment by Lezek123** [comment]
- I found it while testing https://github.com/Joystream/joystream/pull/4084
- I encountered it on https://github.com/Joystream/joystream/pull/4084, but it's also present in `carthage`
- There are no integration tests that trigger this extrinsic (it's a new one introduced in `audit3`/`carthage`)

**Comment by Lezek123** [comment]
Fixed in https://github.com/Joystream/joystream/pull/4110
