### ISSUE TITLE
cli installation fails

### ISSUE THREAD

**Issue by traumschule** [Joystream/joystream#4500]
Command takes a long time and finally fails.

`npm install -g @joystream/cl`
```
18703 verbose stack Error: iso-constants@0.1.2 install: `node build.js > index.browser.js`
18703 verbose stack Exit status 2
18703 verbose stack     at EventEmitter.<anonymous> (/root/.volta/tools/image/node/14.21.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18703 verbose stack     at EventEmitter.emit (events.js:400:28)
18703 verbose stack     at ChildProcess.<anonymous> (/root/.volta/tools/image/node/14.21.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18703 verbose stack     at ChildProcess.emit (events.js:400:28)
18703 verbose stack     at maybeClose (internal/child_process.js:1088:16)
18703 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
18704 verbose pkgid iso-constants@0.1.2
18705 verbose cwd /root
18706 verbose Linux 5.10.0-18-amd64
18707 verbose argv "/root/.volta/tools/image/node/14.21.1/bin/node" "/root/.volta/tools/image/node/14.21.1/bin/npm" "install" "-g" "@joystream/cli"
18708 verbose node v14.21.1
18709 verbose npm  v6.14.17
18710 error code ELIFECYCLE
18711 error errno 2
18712 error iso-constants@0.1.2 install: `node build.js > index.browser.js`
18712 error Exit status 2
18713 error Failed at the iso-constants@0.1.2 install script.
18713 error This is probably not a problem with npm. There is likely additional logging output above.
18714 verbose exit [ 2, true ]
```

env debian 11.5
```
root@joystreamstats:~# npm --version
6.14.17
root@joystreamstats:~# node --version
v14.21.1
```

## Solution
Can this be simplified?

Not sure if there could be faster recommended way to install.

For example a binary release like for `joystream-node`. Or is there?

**Comment by traumschule** [comment]
Thanks @Lezek123!
> Ok, I was able to reproduce the exact same issue
> I did some digging and it looks like the answer can be found here: https://github.com/ipfs/js-ipfs/issues/3241#issuecomment-678953760
> Instead you should either use a node version manager like nvm or n which will install everything in your home directory, or if you have node installed globally, make sure your current user can write to /usr/local/lib/node_modules before doing the install.
