### ISSUE TITLE
Storage server stuck in  a sync loop

### ISSUE THREAD

**Issue by yasiryagi** [Joystream/joystream#4627]
```
2023-02-10 16:15:38:1538 info: Sync ended.
2023-02-10 16:15:38:1538 info: Sync paused for 1 minute(s).
2023-02-10 16:15:39:1539 http: HTTP GET /api/v1/version
2023-02-10 16:15:41:1541 http: HTTP GET /api/v1/version
2023-02-10 16:15:52:1552 http: HTTP GET /api/v1/version
2023-02-10 16:16:00:160 http: HTTP GET /api/v1/state/data
2023-02-10 16:16:00:160 http: HTTP GET /api/v1/state/data
2023-02-10 16:16:01:161 http: HTTP GET /api/v1/version
2023-02-10 16:16:20:1620 http: HTTP GET /api/v1/version
2023-02-10 16:16:22:1622 http: HTTP GET /api/v1/version
2023-02-10 16:16:30:1630 http: HTTP GET /api/v1/state/data
2023-02-10 16:16:30:1630 http: HTTP GET /api/v1/state/data
2023-02-10 16:16:38:1638 info: Resume syncing....
2023-02-10 16:16:38:1638 info: Started syncing...
2023-02-10 16:16:38:1638 debug: Query - storageBucketsConnection
2023-02-10 16:16:38:1638 debug: Sync - getting all storage buckets: offset = 0, limit = 1000
2023-02-10 16:16:38:1638 debug: Query - storageBagsConnection
2023-02-10 16:16:39:1639 http: HTTP GET /api/v1/version
2023-02-10 16:16:39:1639 debug: Query - storageBagsConnection
2023-02-10 16:16:40:1640 debug: Query - storageBagsConnection
2023-02-10 16:16:40:1640 debug: Query - storageBagsConnection
2023-02-10 16:16:41:1641 debug: Query - storageBagsConnection
2023-02-10 16:16:42:1642 debug: Query - storageBagsConnection
2023-02-10 16:16:42:1642 http: HTTP GET /api/v1/version
2023-02-10 16:16:42:1642 debug: Query - storageBagsConnection
2023-02-10 16:16:43:1643 debug: Query - storageBagsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Query - storageDataObjectsConnection
2023-02-10 16:16:43:1643 debug: Sync - new objects: 1
2023-02-10 16:16:43:1643 debug: Sync - obsolete objects: 7
2023-02-10 16:16:43:1643 debug: Sync - started processing...
2023-02-10 16:16:43:1643 debug: Sync - preparing for download of: 521 ....
2023-02-10 16:16:43:1643 warn: Sync - cannot get operator URLs for 521
2023-02-10 16:16:43:1643 info: Sync ended.
2023-02-10 16:16:43:1643 info: Sync paused for 1 minute(s).
2023-02-10 16:16:50:1650 http: HTTP GET /api/v1/version
2023-02-10 16:17:00:170 http: HTTP GET /api/v1/state/data
2023-02-10 16:17:00:170 http: HTTP GET /api/v1/state/data
2023-02-10 16:17:02:172 http: HTTP GET /api/v1/version
2023-02-10 16:17:20:1720 http: HTTP GET /api/v1/version
2023-02-10 16:17:22:1722 http: HTTP GET /api/v1/version
2023-02-10 16:17:30:1730 http: HTTP GET /api/v1/state/data
2023-02-10 16:17:30:1730 http: HTTP GET /api/v1/state/data
2023-02-10 16:17:39:1739 http: HTTP GET /api/v1/version
2023-02-10 16:17:43:1743 info: Resume syncing....
2023-02-10 16:17:43:1743 info: Started syncing...
2023-02-10 16:17:43:1743 debug: Query - storageBucketsConnection
2023-02-10 16:17:43:1743 debug: Sync - getting all storage buckets: offset = 0, limit = 1000
2023-02-10 16:17:43:1743 debug: Query - storageBagsConnection
2023-02-10 16:17:44:1744 debug: Query - storageBagsConnection
2023-02-10 16:17:45:1745 debug: Query - storageBagsConnection
2023-02-10 16:17:46:1746 debug: Query - storageBagsConnection
2023-02-10 16:17:46:1746 debug: Query - storageBagsConnection
2023-02-10 16:17:46:1746 http: HTTP GET /api/v1/version
2023-02-10 16:17:47:1747 debug: Query - storageBagsConnection
2023-02-10 16:17:47:1747 debug: Query - storageBagsConnection
2023-02-10 16:17:48:1748 debug: Query - storageBagsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Query - storageDataObjectsConnection
2023-02-10 16:17:48:1748 debug: Sync - new objects: 1
2023-02-10 16:17:48:1748 debug: Sync - obsolete objects: 7
2023-02-10 16:17:48:1748 debug: Sync - started processing...
2023-02-10 16:17:48:1748 debug: Sync - preparing for download of: 521 ....
2023-02-10 16:17:48:1748 warn: Sync - cannot get operator URLs for 521
2023-02-10 16:17:48:1748 info: Sync ended.
2023-02-10 16:17:48:1748 info: Sync paused for 1 minute(s).
2023-02-10 16:17:50:1750 http: HTTP GET /api/v1/version
2023-02-10 16:18:00:180 http: HTTP GET /api/v1/state/data
2023-02-10 16:18:00:180 http: HTTP GET /api/v1/state/data
2023-02-10 16:18:02:182 http: HTTP GET /api/v1/version
2023-02-10 16:18:20:1820 http: HTTP GET /api/v1/version
2023-02-10 16:18:21:1821 http: HTTP GET /api/v1/version
2023-02-10 16:18:24:1824 error: GET /api/v1/521: Error 200: not found
2023-02-10 16:18:24:1824 http: HTTP GET /api/v1/521
2023-02-10 16:18:30:1830 http: HTTP GET /api/v1/state/data
2023-02-10 16:18:30:1830 http: HTTP GET /api/v1/state/data
2023-02-10 16:18:30:1830 http: HTTP GET /api/v1/files/521
2023-02-10 16:18:30:1830 error: GET /api/v1/files/521: Error 404: ENOENT: no such file or directory, open '/data/521'
Error: ENOENT: no such file or directory, open '/data/521'
    at Object.openSync (fs.js:498:3)
    at Function.module.exports.sync (/joystream/node_modules/with-open-file/index.js:19:17)
    at Function.module.exports.sync (/joystream/node_modules/read-chunk/index.js:30:33)
    at getFileInfo (/joystream/storage-node/src/services/helpers/fileInfo.ts:39:28)
    at getFile (/joystream/storage-node/src/services/webApi/controllers/filesApi.ts:43:39)
    at Layer.handle [as handle_request] (/joystream/node_modules/express/lib/router/layer.js:95:5)
    at next (/joystream/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/joystream/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/joystream/node_modules/express/lib/router/layer.js:95:5)
    at /joystream/node_modules/express/lib/router/index.js:284:15
2023-02-10 16:18:33:1833 http: HTTP GET /api/v1/version
2023-02-10 16:18:39:1839 http: HTTP GET /api/v1/version
2023-02-10 16:18:48:1848 info: Resume syncing....
2023-02-10 16:18:48:1848 info: Started syncing...
2023-02-10 16:18:48:1848 debug: Query - storageBucketsConnection
2023-02-10 16:18:48:1848 debug: Sync - getting all storage buckets: offset = 0, limit = 1000
2023-02-10 16:18:49:1849 debug: Query - storageBagsConnection
2023-02-10 16:18:49:1849 debug: Query - storageBagsConnection
2023-02-10 16:18:50:1850 http: HTTP GET /api/v1/version
2023-02-10 16:18:50:1850 debug: Query - storageBagsConnection
2023-02-10 16:18:51:1851 debug: Query - storageBagsConnection
2023-02-10 16:18:51:1851 debug: Query - storageBagsConnection
2023-02-10 16:18:52:1852 debug: Query - storageBagsConnection
2023-02-10 16:18:52:1852 debug: Query - storageBagsConnection
2023-02-10 16:18:53:1853 debug: Query - storageBagsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:53:1853 debug: Query - storageDataObjectsConnection
2023-02-10 16:18:54:1854 debug: Sync - new objects: 1
2023-02-10 16:18:54:1854 debug: Sync - obsolete objects: 7
2023-02-10 16:18:54:1854 debug: Sync - started processing...
2023-02-10 16:18:54:1854 debug: Sync - preparing for download of: 521 ....
2023-02-10 16:18:54:1854 warn: Sync - cannot get operator URLs for 521
2023-02-10 16:18:54:1854 info: Sync ended.
2023-02-10 16:18:54:1854 info: Sync paused for 1 minute(s).
2023-02-10 16:19:00:190 http: HTTP GET /api/v1/state/data
2023-02-10 16:19:00:190 http: HTTP GET /api/v1/state/data
2023-02-10 16:19:02:192 http: HTTP GET /api/v1/version
2023-02-10 16:19:20:1920 http: HTTP GET /api/v1/version
2023-02-10 16:19:21:1921 http: HTTP GET /api/v1/version
2023-02-10 16:19:30:1930 http: HTTP GET /api/v1/state/data
2023-02-10 16:19:30:1930 http: HTTP GET /api/v1/state/data
2023-02-10 16:19:33:1933 http: HTTP GET /api/v1/version
2023-02-10 16:19:39:1939 http: HTTP GET /api/v1/version
2023-02-10 16:19:50:1950 http: HTTP GET /api/v1/version
2023-02-10 16:19:54:1954 info: Resume syncing....
2023-02-10 16:19:54:1954 info: Started syncing...
2023-02-10 16:19:54:1954 debug: Query - storageBucketsConnection
2023-02-10 16:19:54:1954 debug: Sync - getting all storage buckets: offset = 0, limit = 1000
2023-02-10 16:19:54:1954 debug: Query - storageBagsConnection
2023-02-10 16:19:54:1954 debug: Query - storageBagsConnection
2023-02-10 16:19:55:1955 debug: Query - storageBagsConnection
2023-02-10 16:19:56:1956 debug: Query - storageBagsConnection
2023-02-10 16:19:56:1956 debug: Query - storageBagsConnection
2023-02-10 16:19:57:1957 debug: Query - storageBagsConnection
2023-02-10 16:19:57:1957 debug: Query - storageBagsConnection
2023-02-10 16:19:58:1958 debug: Query - storageBagsConnection
2023-02-10 16:19:58:1958 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:58:1958 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:58:1958 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:58:1958 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:58:1958 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:59:1959 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:59:1959 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:59:1959 debug: Query - storageDataObjectsConnection
2023-02-10 16:19:59:1959 debug: Sync - new objects: 1
2023-02-10 16:19:59:1959 debug: Sync - obsolete objects: 7
2023-02-10 16:19:59:1959 debug: Sync - started processing...
2023-02-10 16:19:59:1959 debug: Sync - preparing for download of: 521 ....
2023-02-10 16:19:59:1959 warn: Sync - cannot get operator URLs for 521
2023-02-10 16:19:59:1959 info: Sync ended.
2023-02-10 16:19:59:1959 info: Sync paused for 1 minute(s).
2023-02-10 16:20:00:200 http: HTTP GET /api/v1/state/data
2023-02-10 16:20:00:200 http: HTTP GET /api/v1/state/data
2023-02-10 16:20:02:202 http: HTTP GET /api/v1/version
2023-02-10 16:20:20:2020 http: HTTP GET /api/v1/version
2023-02-10 16:20:21:2021 http: HTTP GET /api/v1/version
2023-02-10 16:20:30:2030 http: HTTP GET /api/v1/state/data
2023-02-10 16:20:30:2030 http: HTTP GET /api/v1/state/data
2023-02-10 16:20:37:2037 http: HTTP GET /api/v1/version
2023-02-10 16:20:39:2039 http: HTTP GET /api/v1/version
2023-02-10 16:20:50:2050 http: HTTP GET /api/v1/version
2023-02-10 16:20:59:2059 info: Resume syncing....
2023-02-10 16:20:59:2059 info: Started syncing...
2023-02-10 16:20:59:2059 debug: Query - storageBucketsConnection
2023-02-10 16:20:59:2059 debug: Sync - getting all storage buckets: offset = 0, limit = 1000
2023-02-10 16:20:59:2059 debug: Query - storageBagsConnection
2023-02-10 16:20:59:2059 debug: Query - storageBagsConnection
2023-02-10 16:21:00:210 http: HTTP GET /api/v1/state/data
2023-02-10 16:21:00:210 http: HTTP GET /api/v1/state/data
2023-02-10 16:21:00:210 debug: Query - storageBagsConnection
2023-02-10 16:21:01:211 debug: Query - storageBagsConnection
2023-02-10 16:21:01:211 debug: Query - storageBagsConnection
2023-02-10 16:21:02:212 http: HTTP GET /api/v1/version
2023-02-10 16:21:02:212 debug: Query - storageBagsConnection
2023-02-10 16:21:02:212 debug: Query - storageBagsConnection
2023-02-10 16:21:03:213 debug: Query - storageBagsConnection
2023-02-10 16:21:03:213 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Query - storageDataObjectsConnection
2023-02-10 16:21:04:214 debug: Sync - new objects: 1
2023-02-10 16:21:04:214 debug: Sync - obsolete objects: 7
2023-02-10 16:21:04:214 debug: Sync - started processing...
2023-02-10 16:21:04:214 debug: Sync - preparing for download of: 521 ....
2023-02-10 16:21:04:214 warn: Sync - cannot get operator URLs for 521
2023-02-10 16:21:04:214 info: Sync ended.
2023-02-10 16:21:04:214 info: Sync paused for 1 minute(s).
```

GraphQl object detail
Channel 7738 is my test channel , I have no object 521 in the server. 
the channel have only one video https://gleev.xyz/channel/7738?tab=Videos which is available 
```

{
  "data": {
    "storageDataObjects": [
      {
        "id": "521",
        "isAccepted": true,
        "stateBloatBond": "394599471",
        "storageBag": {
          "id": "dynamic:channel:7738",
          "storageBuckets": [
            {
              "id": "0",
              "operatorMetadata": {
                "nodeEndpoint": "https://joystream.yyagi.cloud/storage/"
              }}]}}]}}


{
  "data": {
    "storageBags": [
      {
        "id": "dynamic:channel:7738",
        "objects": [
          {
            "id": "521",
            "isAccepted": true,
            "createdAt": "2023-01-16T09:43:36.000Z"
          },
          {
            "id": "772",
            "isAccepted": true,
            "createdAt": "2023-01-24T11:10:30.000Z"
          },
          {
            "id": "770",
            "isAccepted": true,
            "createdAt": "2023-01-24T11:09:00.000Z"
          }
        ]
      }
    ]
  }
}
```

I can locate object 770 and 772 in the server.

**Comment by Lezek123** [comment]
I don't see anything unusual about how the node is handling a missing file here:
- You are the only storage provider that is supposed to have the file in question (`521`), so if you don't have it, you won't be able to sync it from anyone else and you'll continue to get `Sync - cannot get operator URLs for 521` warning during sync (note it's just a warning, it's not breaking the sync process itself)
- You have `syncInterval` set to one minute, so the node is trying to re-sync every minute and hence you'll get a lot of logs like this.
- `2023-02-10 16:18:30:1830 error: GET /api/v1/files/521: Error 404: ENOENT: no such file or directory` I think is a standard log you get when someone is accessing https://joystream.yyagi.cloud/storage/api/v1/files/521 and gets a `{"type":"files","message":"File not found."}` response

Now the main question is why you don't have file `521`. Did you have it before? Are you able to tell when you lost it?

**Comment by traumschule** [comment]
This is more a design question in combination with best practice log monitoring: is there a huge benefit in logging this every minute vs in greater intervals or hourly summaries:
```
X assets in store
Z/C total storage used
Y recent errors
```
Or even a new public API URL to fetch latest errors?

**Comment by yasiryagi** [comment]
It seems this was a false alert. I wrote a quick to query the QN for how many files each node should have and it seems the number match.

```
/data/joystream-storage # ls -l | wc -l
640
 # python3 print_objs.py | grep ' 0 ' | wc -l
637
 # python3 print_objs.py | grep ' 4 ' | wc -l
1161
 # python3 print_objs.py | grep ' 1 ' | wc -l
1109
 # python3 print_objs.py | grep ' 2 ' | wc -l
727
 # python3 print_objs.py | grep ' 3 ' | wc -l
1134
 # python3 print_objs.py | wc -l
1188
```

I will create a proposal ticket regarding logs and metrics collection next week. 

Now regarding the missing file; it is assigned to my test channel 7738. This channel only point to my node for testing and I only uploaded only one file and everything seems fine https://gleev.xyz/channel/7738?tab=Videos.

**Comment by yasiryagi** [comment]
Also the error below need to be handled better 

```
2023-02-10 16:18:30:1830 error: GET /api/v1/files/521: Error 404: ENOENT: no such file or directory, open '/data/521'
Error: ENOENT: no such file or directory, open '/data/521'
    at Object.openSync (fs.js:498:3)
    at Function.module.exports.sync (/joystream/node_modules/with-open-file/index.js:19:17)
    at Function.module.exports.sync (/joystream/node_modules/read-chunk/index.js:30:33)
    at getFileInfo (/joystream/storage-node/src/services/helpers/fileInfo.ts:39:28)
    at getFile (/joystream/storage-node/src/services/webApi/controllers/filesApi.ts:43:39)
    at Layer.handle [as handle_request] (/joystream/node_modules/express/lib/router/layer.js:95:5)
    at next (/joystream/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/joystream/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/joystream/node_modules/express/lib/router/layer.js:95:5)
    at /joystream/node_modules/express/lib/router/index.js:284:15
    ```

**Comment by bedeho** [comment]
Perhaps you can have a standalone issue for this last one?
