### ISSUE TITLE
Argus trying to set headers after response is set

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4760]
Seeing those in my logs from time to time:
```
2023-05-15 14:24:22:2422 PublicApi error: middlewareError
{
    "err": {
        "code": "ERR_HTTP_HEADERS_SENT",
        "message": "Cannot set headers after they are sent to the client",
        "stack": "Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (internal/errors.js:322:7)\n    at ServerResponse.setHeader (_http_outgoing.js:561:11)\n    at PublicApiController.assetHead (/joystream/distributor-node/src/services/httpApi/controllers/public.ts:224:9)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /joystream/distributor-node/src/services/httpApi/HttpApiBase.ts:30:9"
    },
    "req": {
        "url": "/api/v1/assets/13702",
        "headers": {
            "host": "joystream.koalva.io",
            "user-agent": "undici",
            "accept": "*/*",
            "accept-encoding": "br, gzip, deflate",
            "accept-language": "*",
            "sec-fetch-mode": "cors",
            "x-forwarded-host": "joystream.koalva.io",
            "x-forwarded-proto": "https"
        },
        "method": "HEAD",
        "httpVersion": "1.1",
        "originalUrl": "/api/v1/assets/13702",
        "query": {}
    }
}
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at PublicApiController.assetHead (/joystream/distributor-node/src/services/httpApi/controllers/public.ts:224:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /joystream/distributor-node/src/services/httpApi/HttpApiBase.ts:30:9
```

**Comment by zeeshanakram3** [comment]
A couple of questions to further investigate this issue:
- Does this error happens only for `HEAD assets/` request
- What is the error code of the response

**Comment by kdembler** [comment]
> Does this error happens only for HEAD assets/ request

No, I've seen this happen also with GET requests

> What is the error code of the response

I'm not sure, I think because of the error, the status code doesn't get logged

**Comment by zeeshanakram3** [comment]
Fixed in https://github.com/Joystream/joystream/pull/4772
