### ISSUE TITLE
[Argus] unhandled exception when QN is unavailable

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4762]
This error was reported by one of the distributors when his QN was having issues
```
2023-05-17 15:36:44:3644 QueryNodeApi error: Error when trying to execute a query!
{
    "err": {
        "message": "Graphql syntax errors found",
        "graphQLErrors": [
            {
                "message": "getaddrinfo EAI_AGAIN db",
                "locations": [
                    {
                        "line": 2,
                        "column": 3
                    }
                ],
                "path": [
                    "storageBucketsConnection"
                ],
                "extensions": {
                    "code": "INTERNAL_SERVER_ERROR",
                    "exception": {
                        "errno": -3001,
                        "code": "EAI_AGAIN",
                        "syscall": "getaddrinfo",
                        "hostname": "db"
                    }
                }
            }
        ]
    }
}
2023-05-17 15:36:44:3644 NetworkingManager error: Couldn't check active storage node endpooints
{
    "err": {
        "message": "Cannot read property 'storageBucketsConnection' of null",
        "stack": "TypeError: Cannot read property 'storageBucketsConnection' of null\n    at QueryNodeApi.multipleEntitiesWithPagination (/root/joystream/distributor-node/src/services/networking/query-node/api.ts:152:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async NetworkingService.checkActiveStorageNodeEndpoints (/root/joystream/distributor-node/src/services/networking/NetworkingService.ts:398:38)"
    }
}
```

```
(node:3358105) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'distributionBuckets' of null
    at QueryNodeApi.multipleEntitiesQuery (/root/joystream/distributor-node/src/services/networking/query-node/api.ts:128:90)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NetworkingService.fetchSupportedDataObjects (/root/joystream/distributor-node/src/services/networking/NetworkingService.ts:376:9)
    at async ContentService.cacheCleanup (/root/joystream/distributor-node/src/services/content/ContentService.ts:48:30)
(node:3358105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1339)
```

**Comment by zeeshanakram3** [comment]
Fixed in https://github.com/Joystream/joystream/pull/4769
