### ISSUE TITLE
Storage Node Tests Race condition 

### ISSUE THREAD

**Issue by mnaamani** [Joystream/joystream#860]
Occasionally the storage tests fail in the storage-node.

This occurs when the storage backend is trying to add the temporary file to ipfs with the following call:

```
# storage-node/packages/storage/storage.js

this.storage.ipfs.addFromFs(this.temp.path)
```

This happens in the `commit()` call which is supposed to be made after the temporary file has been written to disk. Normally after emission of the `finish` event on the underlying stream. The ipfs-http-client however sometimes errors and reports that the file was not found.

Initially I thought this was due to the ipfs node running inside a docker container and didn't have access to the host location of the file. But that is not the case. It is only the ipfs-http-client that needs access.

Given that the error is only showing up sometimes suggests it is a race condition. In the tests I've tried to resolve it by ensuring the call to commit() happens on the next tick, using process.nextTick() but I still see this issue.

Perhaps it is some bug in the `temp` npm package? 
We do use the `.track()` functionality which cleans up the temp file on exit, is it perhaps doing the cleanup too early?
The mocha tests do run with `--exit` argument.. is this having an impact?

We haven't seen this "bug" in production so perhaps (hopefully) it is only occuring in the tests, but it would be good to get to the bottom of it.

```
 | (node:93698) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/var/folders/x1/jzcg_82x2yndlklx7ystth580000gn/T/s-202062-93698-s6ytvk.ba0z'
 |     at Object.statSync (fs.js:855:3)
 |     at loadPaths (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/src/utils/prepare-file.js:21:20)
 |     at flatmap (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/src/utils/prepare-file.js:118:14)
 |     at /Users/mokhtar/joystream/joystream/node_modules/flatmap/index.js:7:20
 |     at Array.forEach (<anonymous>)
 |     at module.exports (/Users/mokhtar/joystream/joystream/node_modules/flatmap/index.js:6:7)
 |     at prepareFile (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/src/utils/prepare-file.js:111:10)
 |     at Duplex.retStream._write (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/src/utils/send-files-stream.js:45:23)
 |     at doWrite (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/node_modules/readable-stream/lib/_stream_writable.js:405:139)
 |     at writeOrBuffer (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/node_modules/readable-stream/lib/_stream_writable.js:394:5)
 |     at Duplex.Writable.write (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/node_modules/readable-stream/lib/_stream_writable.js:303:11)
 |     at /Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/src/utils/send-one-file-multiple-results.js:15:12
 |     at Function.promisify (/Users/mokhtar/joystream/joystream/node_modules/ipfs-packages/storage/http-client/src/files-regular/add-from-fs.js:38:5)
 |     at /Users/mokhtar/joystream/joystream/node_modules/promisify-packages/storage/es6/index.js:41:20
 |     at new Promise (<anonymous>)
 |     at Object.addFromFs (/Users/mokhtar/joystream/joystream/node_modules/promisify-packages/storage/es6/index.js:35:16)
 |     at StorageWriteStream.commit (/Users/mokhtar/joystream/joystream/storage-packages/storage/node/packages/storage/storage.js:160:23)
 |     at StorageWriteStream.stream.on (/Users/mokhtar/joystream/joystream/storage-packages/storage/node/packages/storage/test/storage.js:39:16)
 |     at StorageWriteStream.emit (events.js:198:13)
 |     at finishMaybe (_stream_writable.js:646:14)
 |     at endWritable (_stream_writable.js:663:3)
 |     at StorageWriteStream.Writable.end (_stream_writable.js:594:5)
 |     at process.nextTick (/Users/mokhtar/joystream/joystream/storage-packages/storage/node/packages/storage/test/storage.js:46:39)
 |     at process._tickCallback (packages/storage/internal/process/next_tick.js:61:11)
 | (node:93698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
 | (node:93698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mnaamani** [comment]
old storage node is deprecated. this issue is no longer relevant.
